Develop
lalalakolpachok/airbnb-demo-frontend pull request #2
Opened 2017-11-09 00:04 UTC by lalalakolpachok

2017-11-09 16:41 UTC, evgenyrodionov commented
Название ПРа должно отражать сделанную работу

не коммить после запроса ревью — я не могу быть уверен что не прилетит ещё 10 коммитов во время проверки

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/BottomNav.js
> +const Item = styled.li`
списки только для списков в тексте

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/Menu/Airbnb.js
> +import Item from "./Item";
итем плохой нейминг

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/Menu/Airbnb.js
> +import Item from "./Item";
неочевидный

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/Select/Item.js
> +const Div = styled.div`position: relative;`;
плохое название компонента

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/Select/Item.js
> +  -webkit-appearance: none;
1) без браузерных префиксов
2) appearance не работает в ие11

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/Select/index.js
> +        <Item name="language" option1="English" option2="Russian" />
опять итем! чем один итем отличается от другого итем?

2017-11-09 16:48 UTC, evgenyrodionov commented on src/Footer/Select/index.js
> +        <Item name="language" option1="English" option2="Russian" />
ну и опять же, ты можешь просто экспортить стилизованный селект и использовать как
<Select>

2017-11-09 16:51 UTC, imevro requested changes

2017-11-09 16:51 UTC, evgenyrodionov commented on src/common/NextPage.js
> +const NextPage = styled.button.attrs({
а зачем вот этот attrs?

2017-11-10 03:22 UTC, lalalakolpachok commented on src/common/NextPage.js
> +const NextPage = styled.button.attrs({
заменила на extend

2017-11-10 13:07 UTC, imevro requested changes

2017-11-10 13:07 UTC, evgenyrodionov commented on src/Footer/Menu/Discover.js
> +            <Link link="#" text="Gift Cards" />
зачем кстати текст передавать пропом? Можно же `<Link link="#">Gift Cards</Link>`

2017-11-10 13:07 UTC, evgenyrodionov commented on src/Footer/Menu/Discover.js
> +            <Link link="#" text="Gift Cards" />
а href можно оставить, тогда не придётся плодить компонент-прокладку вот здесь https://github.com/lalalakolpachok/airbnb-demo-frontend/pull/2/files/81f6b78010e62d13e8a9f3bc92d58f614127d301..21261f8ddead824c85ab6400d25975b10120ed98#diff-2155a7cd557a3756e4defa9152fdee00R22

2017-11-10 13:07 UTC, evgenyrodionov commented on src/Main/Explore/Card.js
> +  <div className="col-xs-6 col-s-5 col-sm-4 col-md-5 col-lg-4">
col-s-5 это что

2017-11-10 13:07 UTC, evgenyrodionov commented on src/Main/Explore/Card.js
> +  <div className="col-xs-6 col-s-5 col-sm-4 col-md-5 col-lg-4">
сетку вынеси в родительский компонент — что ты будешь делать когда тебе понадобится эту же карточку использовать в другой сетке?

2017-11-11 11:22 UTC, imevro requested changes

2017-11-11 11:22 UTC, evgenyrodionov commented on src/Experiences/index.js
> +import NextPage from "../common/NextPage";
а почему бы это всё не объединить с кучей экспортов в один UI.js?

2017-11-11 11:22 UTC, evgenyrodionov commented on src/Footer/Copyright.js
> +  return <Text>© Airbnb Inc.</Text>;
а зачем? компонент-прокладка

2017-11-12 11:46 UTC, imevro requested changes

2017-11-12 11:46 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "Create Airbnb App",
wtf

2017-11-12 11:46 UTC, evgenyrodionov commented on src/Explore/Card.js
> +  <Card href={props.link}>
href={link} согласованности мало

2017-11-12 11:50 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "Create Airbnb App",
это же название приложения

2017-11-12 13:30 UTC, merged

2017-11-12 13:30 UTC, evgenyrodionov commented
Сделай пулл в мастере